#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ahavrius <ahavrius@student.unit.ua>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/02 20:08:29 by ahavrius          #+#    #+#              #
#    Updated: 2019/04/02 20:08:30 by ahavrius         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

FLAGS = -Werror -Wall -Wextra
NAME = replace

all:
	clang++ $(FLAGS) -o $(NAME) main.cpp
fclean:
	rm $(NAME)
re: fclean all