#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ahavrius <ahavrius@student.unit.ua>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/01 14:34:54 by ahavrius          #+#    #+#              #
#    Updated: 2019/04/01 14:34:55 by ahavrius         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

FLAGS = -Werror -Wall -Wextra

all:
	clang++ $(FLAGS) -o megaphone megaphone.cpp
fclean:
	rm -f megaphone
re: fclean all