#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ahavrius <ahavrius@student.unit.ua>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/01 15:33:38 by ahavrius          #+#    #+#              #
#    Updated: 2019/04/01 15:33:39 by ahavrius         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = phonebook
SRC = PhoneBook.cpp main.cpp
FLAGS = -Wall -Werror -Wextra

all:
	g++ $(FLAGS) -o $(NAME) $(SRC)
clean:
	rm $(NAME)
